#
# Github site is https://jonathanwiebe1.github.io/site/
#
title: Jonathan Wiebe - Health Architecture Consulting
email: jw.consulting.site@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  A health architecture and standards expert specializes in designing and implementing frameworks 
  that ensure the effective integration of health information systems. They possess in-depth 
  knowledge of healthcare regulations, interoperability standards, and best practices in data 
  management and general solution and enterprise architecture. 
#By collaborating with healthcare providers, technology developers, and regulatory 
#bodies, they create scalable solutions that enhance patient care, improve data exchange, and 
#promote compliance with industry standards. Their expertise helps streamline processes, ensuring 
#that health information systems are secure, efficient, and aligned with evolving healthcare needs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: jonathanwiebe1
linkedin_username: jonathan-wiebe1

# Build settings
theme: minima
plugins:
  - jekyll-feed
